# Build all examples 

all: build

build:
	g++ dataTypes.cpp -o dataTypes
	g++ hello_world.cpp -o hello_world
	g++ io.cpp -o io
	gcc parseMsg.c -o parseMsg
	gcc splitStrByDem.c -o splitStrByDem
	gcc split_str.c -o split_str	

clean:
	rm -f dataTypes hello_world io parseMsg splitStrByDem split_str
	rm -f *.bin
