#include <stdio.h>
#include<string.h>
main () {
     
     int p;
     
     int n,temp, tmp2, i;

     printf("Digite numero= \n");     
     scanf("%i", &n);
     temp=n;
     i=0;
        
     while(temp>=10)
     {
                    tmp2=temp/10;                  
                    temp=tmp2;
                    i++;    
     }
     i=i+1;
     
    // printf ("\nA qtd de digitos eh %i",i);  
  
  p=pow(10,(i-1));
  //i=4;
den=i;
while(den>1){
             
             if ((n/p)!=(((n%p)%pow(10,i-2))%pow(10,i-3)) return false;
             
             
             
  
  
  
  
     
     getchar();
     getchar();
     }
