#include "stdio.h"
#include "stdlib.h"

main ()
{
     int argc;
     char argv[50];
     FILE *fp;
     char ch;
     /*
     if (argc!=2){
                  printf ("Voce esqceu de digitar o nome do aequivo!\n");
                  exit (1);
     }
     
     if ((fp=fopen(argv[1], "w"))==0) {
                            printf ("O aquivo nao pode ser aberto");
                            exit (1);
     }
     
     do {
         ch = getchar();
         putc(ch, fp);
         }while(ch!='$');
         
         fclose(fp);
     }*/
     
     fopen ("ex01.c");
     }
